### ISSUE TITLE
Emissions Target Incorrect in First Year

### ISSUE THREAD

**Issue by tumblerer** [farhanrahman/kyoto#110]
The emissions target set for the first year is incorrect.

It sets it to that countries 1990 value of carbon output.

**Comment by jjonnnyy** [comment]
This is correct according to the formulas we worked out before. What do you think it should be?

**Comment by tumblerer** [comment]
Assuming theres only one country, you should need a drop of 0.995 in the first year.

But you know what?  Maybe that is fine for the moment.  Some countries will still need to reduce to get themselves back to near 1990 levels.

Leave it, for the moment.

**Comment by tumblerer** [comment]
The issue is, if you dont make a 0.995 drop in the first year, you won't get down to 0.950 by year 10.

**Comment by jjonnnyy** [comment]
Ok, I get your point. The reason will be because we defined the year target as:

target  = last session target - (difference between last and current session target \* session progress) - penalty

Where session progress is:

(current year % years in session) / years in session

Therefore year 0 will be session progress 0.0 and year 9 will have session progress 0.9

I could correct it so that the first year (zero) will be session progress 0.1 but it doesn't really make a difference - it will just shift the targets by one year.

**Comment by tumblerer** [comment]
I think it means that you won't end up doing a 0.1 shift in one year as opposed to 0.05 shift.  Doing it right is best.

**Comment by jjonnnyy** [comment]
No because difference between the session targets is 5% (if there is only one agent) therefore producing a 0.5% reduction each year regardless of whether that starts at 0 or 1.
