### ISSUE TITLE
Emissions Target goes negative when member countries can't reduce enough

### ISSUE THREAD

**Issue by Sergeus** [farhanrahman/kyoto#111]
I've created a simulation where there are two agents, one annex one country and one rogue state.   The rogue state produces vastly more carbon emissions than the annex one country.   When global emissions are such that a 5% reduction in overall emissions is greater than the annex one country's total emissions, the emissions target for the annex one country becomes negative.   (There are then many other cascading bugs because of that.)

**Comment by jjonnnyy** [comment]
Well we knew this was possible since we designed the formulas. The question is how do we want to handle it?

I suggest we either ignore it on the condition that we don't run our simulations with parameters that will make this happen or set a cap on the max session reduction that can be applied to annexone countries.
