### ISSUE TITLE
Behaviours completion

### ISSUE THREAD

**Issue by piotroslaw** [farhanrahman/kyoto#132]
Could all of the behaviour writers comment on their porgress here?

We need to do the simulations and balancing today at uni - remember that people need to write the report on the results and submit it tomorrow, so let's make their life easier and have it done asap.

Annex One Sustain:
- Individual behaviour (investments) - done, tested (except long periods of time)
- Balancing - done
- Trading - done, synthetically tested, need to simulate with other agents to ensure correctness

**Comment by piotroslaw** [comment]
@whitebloodcell @Raamaa @n1kunj @georgePil

**Comment by n1kunj** [comment]
Individual behaviour (investments) - working perfectly. Will pretty much always hit our required target by the optimal means in local synthetic tests and on the server.

Balancing - no idea.

Trading - should work in theory. Tested locally, when it sees a good price it will buy.  However the one simulation on the server that could confirm it works in a group environment had GDPs set 10^-6 lower than they should have. Needless to say, my countries shat themselves and [shut down everything](http://i.imgur.com/Ygq4z.jpg) rather than buy. At the very least, the test did confirm my half assed market analysis tool does work and can figure out the current market prices quite well.

**Comment by piotroslaw** [comment]
ok, should we meet in college at about 13:15 to start simulations?

**Comment by tmclayson** [comment]
Already in college but unlikely to be ready by 13:15 to start simulations. Have not yet implemented the join/leave Kyoto logic, but should not take long. s testing to see if the variables controlling my behaviour are achievable, and adjusting if not. i.e. The reduction targets I set for my my agent were overly optimistic, so all money would be spent on that before any investment in industry etc.

**Comment by piotroslaw** [comment]
ok, I will be in at 13:30, you (Tom) mainly interact with George as far as I know, so arrange your tests with him

**Comment by georgePil** [comment]
Non Annex One:

Individual behaviour: done , tested, works perfectly

CDM: done , tested with TradeAgent, works perfectly .. waiting to test with other countries when done

Who is implementing CDM in their behaviour except @piotroslaw  that I know is not implementing? I know @n1kunj  does/will do. @whitebloodcell ? @Raamaa  ?

**Comment by tmclayson** [comment]
Yes I am implementing CDM
