### ISSUE TITLE
Not enough game strategies?

### ISSUE THREAD

**Issue by oliviervg1** [farhanrahman/kyoto#19]
Nik believes that there aren't enough possible strategies for country behaviours and that everyone would just act on the last tick of each year.

To spread trades/investments more, it was suggested to introduce a spending cap per tick.

**Comment by piotroslaw** [comment]
The counterargument was that the ticks were introduced only to give trading enough time (remember every transaction is 3 ticks), so there is nothing wrong in investments being done only in the last tick.

Also, in case of ex-commies countries, this will actually not be the case - Russia and company will invest during the entire year if we think we can sell resulting offset at higher price than the investment cost (since we are greedy bastards who are only in kyoto for profit). So while this is potentially a limiting factor for EU countries, I don't think it really is an issue for entire game.

**Comment by azyzio** [comment]
Why is Nik not posting here if has an issue?
I don't understand why would the countries do everything in the last tick, the prices on the "market" are going to change every tick so the countries will be definitely performing trades throughout the whole year.

The issue I may see (although I am not entirely convinced) is that some countries may invest in carbon reduction/absorbtion/factories during the last tick of the year. I think we should leave this up to the countries because, as Piotr said, this won't be an issue for all of them.

Nik, if you agree, please close the issue.

**Comment by oliviervg1** [comment]
I have to agree with Adam here. I think there are more than enough strategies allowed by our simulation.

Until there is actual proof of the contrary, I am closing this issue.

**Comment by n1kunj** [comment]
I somewhat misunderstood the rules of the game, so I spent the last day thinking about EU strategies. So, it turns out that the issue isn't going to be that there aren't enough strategies. The issue is whether we can balance the game enough to make a lot of these strategies viable. That's a problem for another day.
