### ISSUE TITLE
getCurrentTick returns 0

### ISSUE THREAD

**Issue by tumblerer** [farhanrahman/kyoto#30]
timeService.getCurrentTick() currently always returns 0.  

This is quite a serious issue as it is used to calculate year ends etc.

**Comment by azyzio** [comment]
How did you find it out? Through simulation or JUnitTesting?
I guess the reason for it is that Time Service is not registered for Event Bus (I don't really understand how it works), but I would like to debug it to make sure. The thing is that I haven't played with running simulations yet.

**Comment by Sergeus** [comment]
Simulation.   I'm working on fixing this now.

**Comment by Sergeus** [comment]
I've got a temporary fix working for now that basically uses SimTime to give tick values.   But the event stuff isn't cooperating, so I've sent Sam Macbeth an email asking him about it.   If anyone is well-versed in event-related setup stuff and can take a look at TimeService on the testing branch, then let me know because I cannot get it to subscribe to the event bus.   (I've done the stuff on the presage2.info Q&A forum, the injected setter literally just never runs for no reason whatsoever.)

**Comment by Sergeus** [comment]
Interesting development with this bug.   Participant environment services (like TimeService) cannot, in this version of presage2, interact with the event bus.   (Explains why it was so frustratingly not working.)   I'm gonna create a new TimeService that's a global environment service so it can generate events, and change our current timeService so it can relate information to agents.

**Comment by azyzio** [comment]
Eh... Presage...

**Comment by Sergeus** [comment]
I have fixed time.   See commits 1ff20b4 and e93aed5.
