### ISSUE TITLE
Test interaction between KyotoUI and Simulation.java

### ISSUE THREAD

**Issue by oliviervg1** [farhanrahman/kyoto#45]

**Comment by farhanrahman** [comment]
Im on it at the moment.. The problem is none of the required data is fixed at the moment so my SimulationData object (JSON to java) is still not finalised so i am currently working on instantiating Participants based on the data that I currently can handle. WIll be changing the SimulationData.java class later on.

**Comment by farhanrahman** [comment]
Okay currently we can load in data from UI and simulation data is also stored onto the database as simulation progresses. So the interface between UI and simulation has been bridged more or less. Only thing that is something that we are looking into is how we can have a run button to run a particular simulation
