### ISSUE TITLE
Carbon Absorption Mechanics

### ISSUE THREAD

**Issue by tumblerer** [farhanrahman/kyoto#50]
carbonAbsorption is effectively the equivalent of carbon offset, except that it is not reset to 0 upon the end of a session.

If this is the case, does it get spent in the same manner as carbon offset when countries do not meet their target?  If so, which takes priority?  If not, does that not make carbonAbsorption the same as carbonOutput?

**Comment by piotroslaw** [comment]
Not really, they are very different.

carbonAbsorption is a measure of how much carbon we absorb per year, FROM carbonOutput. So if carbonOutput is 100, and carbonAbsorption is 30, we effectively emit 70 to atmosphere. Hence, if our target is 60, we "lose" 10 carbonOffset.

Provided we don't change anything, the carbonOffset will decrease every year. It is sort of a carbon "currency", and the only thing that is changed as a result of us not meeting / exceeding emissions target, and also the only thing that we can actually trade. No matter what you do, your carbonAbsorption depends ONLY on the amount of forests you have planted since the start, just as carbonOutput depends ONLY on your industry, and they can ONLY be changed by investing in reduction/absorption.

The reason why they are not the same variable (i.e., why absorption doesn't simply reduce output) is that, if they were, planting trees would increase your clean industry measure, and hence would make it more expensive to actually reduce the carbon you produce. Which obviously doesn't make sense.

But they should be considered in conjunction, in a sense that the amount of carbon you emit to atmosphere (which is compared with emissionTarget) is always eqal to carbonOutput - carbonAbsorption.

Does that answer the question?

**Comment by tumblerer** [comment]
I forgot about the effects on the cost of carbon reduction.
