### ISSUE TITLE
Problem with updating carbon offset yearly

### ISSUE THREAD

**Issue by farhanrahman** [farhanrahman/kyoto#55]
In the testtrade branch I found a bug in updating the carbon offset yearly. What I did was the following:

1) Ran the simulation for 730 ticks. The reported carbonOffset at the end was :

Farhan: -440.0
Stuart: 440.0

2) I ran the simulation for 731 ticks. The reported carbonOffset at the end was:

Farhan: -28440.0
Stuart: -27560

Now its correct in the sense that Farhan has less carbonOffset because in the simulation Stuart was always buying. But when I uncomment the updateCarbonOffsetYearly() I get the following output:

Farhan: -440
Stuart: 440

This is correct as Trade doesn't happen until after a few more ticks from tick 730. Just to verify that, I ran the sim for 1000 ticks and the results are:

Farhan: -780
Stuart: 780

**Comment by tumblerer** [comment]
This is because of the way carbonOffsets are subtracted at the end of the year to make up the difference between carbonOutput and emissionTargets.

What should happen is: 
*If offset is already negative, no subtraction should be performed
*If the offset is positive, but not enough to make up the difference - the offset should be subtracted until it is 0, but not into negative values

**Comment by tumblerer** [comment]
Should be fixed.
