### ISSUE TITLE
Sanctions for not meeting the target

### ISSUE THREAD

**Issue by azyzio** [farhanrahman/kyoto#7]
Did we decide on the method to apply sanctions on countries that have not met their targets.
I guess that unlike sanctioning for cheating, there should be no sin counting.
I will implement it when we agree on the method.

**Comment by tumblerer** [comment]
Agreed, there no sin bin for failing to meet targets.

**Comment by azyzio** [comment]
Ok, I did some reading on how it operates in Kyoto protocol and I think we could follow those rules in the game (wasn't it the aim of it? :D)

How it works is:
The emission target for a given period is decreased by the standard emission target change plus the difference in emission and target increased by 30%.
It is easier to illustrate on the example:
Country A has a target of 1000 million CO2
It produces 1001 million CO2
It hasn't met its goal by 1 million CO2, so the goal for the next year will be
995 (1000 - 0.5% \* 1000) - 1 (difference between emission and target) \* 1.3 (increased by 30%) = 993.7 million CO2

As there are no financial sanctions, I wouldn't implement them. Tell me what you think

Source of my knowledge: http://www.cicero.uio.no/fulltext/index_e.aspx?id=3029

**Comment by farhanrahman** [comment]
I think that is a very good way of doing sanctioning. We should stick to that.

**Comment by tumblerer** [comment]
As devil's advocate, thats not really much of a sanction.  If I fail to meet the target this year, my target next year simply gets harder.  There's not much motivation for me to meet it next year, if I know there are no real repercussions. I think the difference between our simulation and the real world is lack of political pressure to fulfil kyoto.  Therefore we need to make some kind of alternative sanction form.

**Comment by piotroslaw** [comment]
While Chris is right that we do not have to stick with real Kyoto rules 100%, there are two problems with different type of sanctioning:
- The countries that do not have targets rely on the fact that reducing carbon output is totally voluntary. We assume that they will want to do it, it is sort of built into the game, and there is no way around it by using some kind of sanctions. It would then be silly to charge the other countries if they failed to meet their target for whatever reason.
- What other charges can there be? Money is pretty stupid, as it would always be a case of what costs less - planting more trees or paying the fee? There's hardly room here for strategy. Likewise, removing country from Kyoto would be even worse, as it would benefit nobody.

So I think we should use the actual Kyoto sanctions here (as Adam proposed) and assume the countries will at least try to meet them. On the other hand, since we allow cheating (not really possible in real life), there should be financial sanctions for it - this opens room for interesting strategies.

**Comment by azyzio** [comment]
I forgot to mention that there is one more punishment defined by Kyoto: a given country is not allowed to sell emissions in the next year.

My suggestions would be: apply Kyoto protocol and add the financial sanction. We can always set the financial punishment to zero to see how the system behaves in a purely Kyoto-based scenario.

**Comment by azyzio** [comment]
I am going to implement this sanctioning today.

**Comment by azyzio** [comment]
Update on implementation:

It is at the moment impossible to implement it fully as the Emission Targeting service doesn't allow anyone but itself to change emission targets in the shared state. The module will be fully functional only when such possibility exists.

**Comment by tumblerer** [comment]
Since countries "grab" emission from the space on the year end, could you not set the countries emissionTarget with the sanctioning body just after they grab the data, and thus overwriting the countries figure.

**Comment by Sergeus** [comment]
I don't think you can do it the way Tory suggests.   The sanction service (is it a service?) needs to communicate changes in emissions target to the emission targetting service so that the changes an persist in some way.

**Comment by azyzio** [comment]
As Stuart says, although the field inside the county will change, the change will be lost as soon as it polls the environment to get the emission target (which would not change as seen by the environment).

To avoid such situations I suggested removing emission target field from the country completely as there might be two different values for the same thing stored in the system.

@jjonnnyy can you say if it would be possible to add the "update" functionality?

**Comment by jjonnnyy** [comment]
Yes, it should be possible to add this functionality. I'm not really sure of the best way to do so yet. 

We could add a amendTarget method to carbonTarget or make carbonTarget check a shared data structure for sanctions before calculating the new target. 

The biggest problem I see is that both monitor and carbonTarget will want to change targets at the end of the year and this may give us some problems with ordering. 

I think it might be better if we rolled the two services into one since both adjust targets?

**Comment by azyzio** [comment]
At the moment the monitor doesn't update the shared state with any sanctioning information but simply applies the changes on the countries. Helping the carbon targeting service seems a good reason to modify it as suggested by Tory in #8.

I was thinking about the ordering problem too. The "standard" yearly reduction should happen first and then the reduction caused by sanctions. If we used the shared state for sanctions notifications, then it should be updated before the carbon targeting happens.

I don't think however that merging the two into one service would be a good idea, monitor has a much broader application than just changing the emission targets.

Two solutions that I can think of:
1. If we could introduce semaphores, we could easily control the order of the execution. Do you think it would be possible?
2. Monitor could actually perform its operation in the last tick of the year, not the first one of the next year. I think it would solve other ordering problems too. It could however have some impact on the strategy of the countries.

**Comment by jjonnnyy** [comment]
The way we have worked this out in the end is to store a penalty value for each country that we factor into it's yearly target calculations (this value then resets at the end of every session). Monitor can then add to this penalty via the setCountryPenalty method in CarbonTarget (this method is package protected).

With this set up it does not matter whether the penalty is added before or after the standard targeting so there is no need to synchronise CarbonTarget and Monitor. 

I am aware that there are still some potential shared data issues within CarbonTarget and I'll try and fix those ASAP.
