### ISSUE TITLE
Unable to spend maximum on carbon reduction

### ISSUE THREAD

**Issue by cmd08** [farhanrahman/kyoto#77]
If you attempt to calculate the maximum reduction you can afford, then proceed to attempt that reduction, an exception is thrown.

``` Java
double reduction = carbonReductionHandler.getCarbonOutputChange(getAvailableToSpend());
carbonReductionHandler.investInCarbonReduction(reduction);
```

Throws a `NotEnoughCashException`.

**Comment by farhanrahman** [comment]
whats the issue with that? its supposed to throw that exception..

**Comment by farhanrahman** [comment]
oops pressed the wrong button

**Comment by cmd08** [comment]
The code asks what the max reduction of CO2 is, given the money available. Then when you try to make a reduction of that amount of CO2, it throws the exception.

**Comment by tumblerer** [comment]
That might be because even though the money you have is enough to give you X carbon reduction, X is greater than the your carbon Output.

What exception is thrown?

**Comment by cmd08** [comment]
NotEnoughCash exception. I've checked that it's well below the carbon output (about 160, compared to 70000)

**Comment by piotroslaw** [comment]
I suppose it is because getCarbonOutputChange is not absolutely precise function - it uses binary search with preset number of iterations to find the carbon output reduction. Reasons for that are in the wiki on google docs (Carbon Reduction / Absorption Model).

**Comment by n1kunj** [comment]
Taking a look now, might take a while as my local branch is well behind and a lot of stuff has changed.

**Comment by n1kunj** [comment]
Fixed and pushed. My binary search had a misplaced divide by 2. Fixed an identical problem in the absorption handler.

**Comment by cmd08** [comment]
This is still broken. Please to be fix?

**Comment by n1kunj** [comment]
Can I get some example code which breaks it?

**Comment by cmd08** [comment]
``` java
double reduction = carbonReductionHandler.getCarbonOutputChange(getAvailableToSpend());
try {
    carbonReductionHandler.investInCarbonReduction(reduction);
    /*These should never ever be thrown happen, we did a runtime check above */
} catch (NotEnoughCarbonOutputException e) {
    throw new RuntimeException(e);
} catch (NotEnoughCashException e) {
    throw new RuntimeException(e);
}
```

**Comment by cmd08** [comment]
@n1kunj please also see the associated commit 9449ce5

**Comment by n1kunj** [comment]
What are the availableToSpend, carbonOutput and energyOutput you initialised the country with?

**Comment by n1kunj** [comment]
Ah, that would make sense - whoever designed the original formula made it round up the number of units instead of down.

Leaving the issue open for now, close it if that fixed it.

**Comment by cmd08** [comment]
It's an almost fix, however it gives unexpected results which are non-consistent.

Please could you take a closer look at this? I think it needs more than a couple of Math.floor()s. Perhaps only ever provide ints in and out (even if you say you can accept floats?) Or perhaps we should respond with an Investment object which ties a cost, co2 together. This would mean the handler could offer similar (but not exact) investments to the country.

**Comment by cmd08** [comment]
As for availableToSpend etc: i'm using uk.ac.ic.kyoto.countries.testCountries.Reduce.java

**Comment by n1kunj** [comment]
Looks like this is an issue for the person that originally wrote the function, which I think was Piotr.

**Comment by piotroslaw** [comment]
looking at this now. which branch are you testing on?

**Comment by piotroslaw** [comment]
Ok, found the "problem", this has been discussed many times, and is also described in wiki page.

You cannot go back and forth (get carbon reduction for given investment and then calculate the price of investment for that reduction) and expect that the values will be exactly the same. And it doesn't matter if we use binary search or exact quadratic equation solving - still, reverse operations on doubles will give slightly different results.

As outlined in wiki and comments, the investment function uses getInvestmentCost function to calculate the cost of reducing carbon by cerain amount, and then subtracts it from your funds. It is safe to first use that function to estimate your cost, and then invest expecting that funds reduced will be exactly the same.

What you are doing instead, is first calculate the carbon you can reduce for a given investment, and then invest (which does the reverse - calculate cost of given reduction). And this is where the exception comes from - the actual cost is sliiightly higher than what you were expecting (or, what getCarbonOutpuChange estimated), and hence higher than what you can spend. What you are checking at runtime is whether reduction is higher than 1 - I have no idea where that comes from and how it is supposed to relate to NotEnoughCashException.

Runding numbers is no solution - this actually made the function less precise. The only system-side solution is to forcibly underestimate the amount of carbon you can get for certain investment, so that you will not attempt to spend too much by investing in it. But it is a pretty bad "fix".

Hence, each agent should take the output of getCarbonOutputChange with a grain of salt, and always check if the actual price of investment (checked with getInvestmentRequired) does not exceed the estimated price that you fed into getCarbonOutputChange, and react accordingly if it does.

**Comment by piotroslaw** [comment]
I have just reversed the changes to rounding, they make matters even worse

**Comment by cmd08** [comment]
Yea, I figured this was the issue. 

We need a better solution to this: either deprecate the function, or return something more useful (perhaps the actual price slightly below the one input, and associated carbon reduction?)

I appreciate the underlying function has no inverse, so we either have to not provide it in the API, or return more useful data.

**Comment by cmd08** [comment]
In 5e968f3211a1eaebc8d721344d7d421db78fbbee I've deprecated the public method. I know this isn't ideal, but I hope it will make people read the JavaDocs!

Also, I've added a while loop in the Reduce country to check that the required cash for a reduction is less than the cost.

I'm going to mark this as a wontfix for this release: seems pointless for now.

**Comment by piotroslaw** [comment]
Deprecating is a good idea - this function is very useful to do a very precise estimation, so removing it altogether would be counterproductive. But people who use it need to keep in mind that it is not 100% exact, and should be used with caution.

Knowingly over/underestimating a return value would be some kind of fix, but I am afraid it would create even more confusion, and I'm not sure sacrificing accuracy is a good idea.

I am closing this for now.
